import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Taller Malandriner de Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>
          Taller <i>malandriner</i> y <u>potente</u>
        </h1>
        <p>
          Aprende Next.js con <mark>las manos sobre el teclado</mark>
        </p>
        <br />
        <p>
          <a href="#">
            <b>Sigue leyendo &rarr;</b>
          </a>
        </p>
      </header>
      <main>
        <hr />
        <section>
          <blockquote>
            "A medio mundo le gustan los perros; y hasta el día de hoy nadie
            sabe qué quiere decir guau"
            <footer>
              <i>- Mafalda</i>
            </footer>
          </blockquote>
        </section>
        <hr />
      </main>
    </>
  );
}
