import Head from "next/head";
import Footer from "../components/footer";
import Header from "../components/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Taller Malandriner de Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <main>
        <hr />
        <section>
          <blockquote>
            "A medio mundo le gustan los perros; y hasta el día de hoy nadie
            sabe qué quiere decir guau"
            <footer>
              <i>- Mafalda</i>
            </footer>
          </blockquote>
        </section>
        <hr />
      </main>
      <Footer></Footer>
    </>
  );
}
